server.servlet.context-path: /demo/api
spring:
  main.banner-mode: off
  servlet.multipart:
    max-file-size: 2MB
    max-request-size: 2MB
    enabled: true

logging.level:
  org.apache.catalina.core: error
  org.apache.tomcat.util.http.parser: error
  org.springframework.boot.web.servlet.context: error
  org.springframework.web.servlet: error
  org.springframework.security.web.DefaultSecurityFilterChain: error
  io.orkes.conductor.client.ApiClient: error

management:
  endpoint.health.access: read_only
  endpoints.access.default: none
